# Generated by Django 3.2.3 on 2021-06-07 21:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активированная')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Преподаватель')),
                ('is_students', models.BooleanField(default=True, verbose_name='Студент')),
                ('name', models.TextField(default=False, max_length=255, verbose_name='Имя')),
                ('last_name', models.TextField(default=False, max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.TextField(blank=True, default=False, max_length=255, verbose_name='Отчество')),
                ('students_groups', models.TextField(default='group', max_length=10, verbose_name='Группа')),
                ('photo', models.ImageField(default='', upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
