# Generated by Django 3.1.2 on 2020-12-17 23:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default=datetime.datetime(2020, 12, 17, 23, 13, 6, 178397, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
