# Generated by Django 3.1.2 on 2020-12-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default='lastname', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='students_groups',
            field=models.TextField(default='group', max_length=10),
        ),
    ]
