# Generated by Django 3.1.2 on 2020-12-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201218_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(default='name', max_length=255),
        ),
    ]
