# Generated by Django 3.1.2 on 2020-12-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201218_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.TextField(default='patronymic', max_length=255),
        ),
    ]
