# Generated by Django 3.2.3 on 2021-05-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210519_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(verbose_name='Активированная'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=False, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(default=False, max_length=255, verbose_name='Имя'),
        ),
    ]
