# Generated by Django 3.2.3 on 2021-06-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='', upload_to='ad_pictures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.TextField(blank=True, default=False, max_length=255, verbose_name='Отчество'),
        ),
    ]
